name: Update AoC Badges

on:
  schedule:
    - cron: '30 11 1-25 12 *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 1594312
          session: ${{ secrets.AO_CSESSION }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ':star: Update badges'
          file_pattern: README.md